ShanYue/shanyue/booking/urls.py
from django.urls import path

from . import views

app_name = 'booking'
urlpatterns = [
    path('', views.index, name='index'),
    path('income/', views.income_input, name='income_input'),
    path('expend/', views.expend_input, name='expend_input'),
    path('income/results/', views.income_results, name='income_results'),
    path('expend/results/', views.expend_results, name='expend_results'),
]

ShanYue/shanyue/shanyue/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('booking.urls')),
    path('admin/', admin.site.urls),
]

ShanYue/shanyue/booking/models.py
from django.db import models

# Create your models here.
class Income(models.Model):
    Income_id = models.AutoField(primary_key=True)
    Income_date = models.DateField('时间',blank=True,null=True)
    Income_money = models.DecimalField('金额', max_digits=9, decimal_places=2, blank=False)
    Income_classify = models.CharField('分类',max_length=200,blank=True,null=True)
    Income_comments = models.CharField('备注',max_length=200,blank=True,null=True)
    Income_record = models.DateTimeField('填写时间',blank=True,null=True)



class Expend(models.Model):
    Expend_id = models.AutoField(primary_key=True)
    Expend_date = models.DateField('时间',blank=True,null=True)
    Expend_money = models.DecimalField('金额', max_digits=9, decimal_places=2, blank=False)
    Expend_classify = models.CharField('分类',max_length=200,blank=True,null=True)
    Expend_comments = models.CharField('备注',max_length=200,blank=True,null=True)
    Expend_record = models.DateTimeField('填写时间',blank=True,null=True)

ShanYue/shanyue/booking/views.py
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from .models import Income,Expend


def index(request):
    return render(request, 'booking/index.html', {})

def income_input(request):
    return render(request, 'booking/income_input.html')

def expend_input(request):
    return render(request, 'booking/expend_input.html', {})

def income_results(request):
    if request.method == 'POST':
        Income_date = request.POST.get('Income_date');
        Income_money = request.POST.get('Income_money');
        Income_classify = request.POST.get('Income_classify');
        Income_comments = request.POST.get('Income_comments');
        Income_record = timezone.now();
        income = Income(Income_date=Income_date, Income_money=Income_money,
                        Income_classify=Income_classify,Income_comments=Income_comments,
                        Income_record=Income_record);
        income.save();
        return render(request, 'booking/income_results.html', {})

def expend_results(request):
    if request.method == 'POST':
        Expend_date = request.POST.get('Expend_date');
        Expend_money = request.POST.get('Expend_money');
        Expend_classify = request.POST.get('Expend_classify');
        Expend_comments = request.POST.get('Expend_comments');
        Expend_record = timezone.now();
        expend = Expend(Expend_date=Expend_date, Expend_money=Expend_money,
                        Expend_classify=Expend_classify,Expend_comments=Expend_comments,
                        Expend_record=Expend_record);
        expend.save();
        return render(request, 'booking/expend_results.html', {})

ShanYue/shanyue/booking/templates/booking/expend_input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>支出记账本</title>
</head>

	<body>
	<center>
	<h1 align="center">支出记账本</h1>
		<form action="{% url 'booking:expend_results'%}" method="post">
			{% csrf_token %}
			<table>
				<tr>
					<td>
						日期：
					</td>
				</tr>
				<tr>
					<td>
						<input type="date" placeholder="请输入日期" name="Expend_date" />
					</td>
				</tr>
				<tr>
					<td>
						金额：
					</td>
				</tr>
				<tr>
					<td>
						<input type="number" placeholder="请输入金额" name="Expend_money" />
					</td>
				</tr>

				<tr>
					<td>
						类别：
						<select name="Expend_classify">
							<option value="餐饮">餐饮</option>
							<option value="娱乐">娱乐</option>
							<option value="保险">保险</option>
							<option value="学习">学习</option>
							<option value="生活用品">生活用品</option>
							<option value="日常开销">日常开销</option>
							<option value="人情">人情</option>
							<option value="其它">其它</option>

						</select>
					</td>
				</tr>
				<tr>
					<td>
						备注： <br/>
						<input type="text" name="Expend_comments"/>
					</td>
				</tr>
				<tr>
					<td>
						<input type="submit" value="保存" />
						<input type="button" value="取消" />
					</td>
				</tr>
			</table>
		</form>
        </center>
	</body>
</html>

ShanYue/shanyue/booking/templates/booking/expend_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>支出记账结果</title>
</head>

<body>
    <h1 align="center">支出记账成功</h1>

    <a href="{% url 'booking:expend_input'%}">再记一笔支出?</a>
</body>
</html>

ShanYue/shanyue/booking/templates/booking/income_input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>收入记账本</title>
</head>

<body>
	<center>
	<h1 align="center">收入记账本</h1>
		<form action="{% url 'booking:income_results'%}" method="post">
			{% csrf_token %}
			<table>
				<tr>
					<td>
						日期：
					</td>
				</tr>
				<tr>
					<td>
						<input type="date" placeholder="请输入日期" name="Income_date" />
					</td>
				</tr>
				<tr>
					<td>
						金额：
					</td>
				</tr>
				<tr>
					<td>
						<input type="number" placeholder="请输入金额" name="Income_money" />
					</td>
				</tr>

				<tr>
					<td>
						类别：
						<select name="Income_classify">
							<option value="工资">工资</option>
							<option value="兼职">兼职</option>
							<option value="理财">理财</option>
							<option value="人情">人情</option>
							<option value="其它">其它</option>

						</select>
					</td>
				</tr>
				<tr>
					<td>
						备注： <br/>
						<input type="text" name="Income_comments"/>
					</td>
				</tr>
				<tr>
					<td>
						<input type="submit" value="保存" />
						<input type="button" value="取消" />
					</td>
				</tr>
			</table>
		</form>
	</center>
</body>
</html>

ShanYue/shanyue/booking/templates/booking/income_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>收入记账结果</title>
</head>
<body>
<h1 align="center">收入记账成功</h1>
<a href="{% url 'booking:income_input'%}">再记一笔收入?</a>
</body>
</html>

ShanYue/shanyue/booking/templates/booking/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人记账本</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'booking/style.css' %}">
</head>
<body>
	<h1 align="center">个人记账本</h1>
	<p align="center">//别想一下造出大海，必须先由小河川开始//</p>
    <div style="text-align:center;vertical-align:middel;margin-top:50px">
		<a href="http://127.0.0.1:8000/income/"><input type="button" style='font-size:18px' value='收入记录'>
        </a>
    </div>

    <div style="text-align:center;vertical-align:middel;;margin-top:80px">
		<a href="http://127.0.0.1:8000/expend/"><input type="button" style='font-size:18px' value='支出记录'>
        </a>
    </div>

</body>
</html>